mqtt:
  broker:
    host: "localhost"
    port: 1883
  clientname: "serverclient"
  username: "server"
  topic:
    temperature: "greenhouse/temperature"
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG